.libPaths(c("renv/library/windows/R-4.5/x86_64-w64-mingw32", .libPaths()))
Sys.setlocale("LC_CTYPE", "Portuguese_Brazil.utf8")
library(haven)
library(data.table)
library(jsonlite)
library(digest)
library(arrow)
setDTthreads(1L)
arrow::set_cpu_count(1L)
arquivo <- "tmp/fechamento_integral_1960/fonte_cem/copia_sav/Censo.1960.brasil.amostra.1.25porcento.sav"
saida <- "tmp/fechamento_integral_1960/fonte_cem/leitura_sav"
if(dir.exists(saida)) stop("A saida da leitura deve ser nova")
dir.create(saida)
piloto <- read_sav(arquivo, n_max = 10L, user_na = TRUE)
print(piloto)
rotulos <- lapply(piloto, attributes)
write_json(rotulos, file.path(saida, "rotulos.json"), auto_unbox = TRUE, pretty = TRUE)
rm(piloto); gc(verbose = FALSE)
dados <- read_sav(arquivo, user_na = TRUE)
setDT(dados)
fwrite(dados[seq_len(min(nrow(dados), 20L))], file.path(saida, "primeiras_linhas.csv"))
resumo <- list(arquivo = arquivo, sha256 = digest(file = arquivo, algo = "sha256"),
               linhas = nrow(dados), colunas = names(dados))
write_json(resumo, file.path(saida, "resumo.json"), auto_unbox = TRUE, pretty = TRUE)
for(col in names(dados)) setattr(dados[[col]], "class", NULL)
write_parquet(dados, file.path(saida, "cem_original.parquet"), compression = "zstd")
print(resumo)
rm(dados); gc(verbose = FALSE)
